function executarOperacao () {
    try {
    throw new Error("Erro gen√©rico");
    } catch ( erro: unknown ) {
        console.log("Erro :", erro as Error );
    }
}

executarOperacao();